version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: finai-mate-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finaimatedb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - finai-net

  backend:
    build: ./backend
    container_name: finai-mate-backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finaimatedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - finai-net

  frontend:
    build: ./frontend
    container_name: finai-mate-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finai-net

volumes:
  db-data:


networks:
  finai-net:
